### Restate

@restate_runtime_base_url = http://localhost:8081

# @name Register services
POST {{restate_runtime_base_url}}/endpoints
content-type: application/json

{
    "uri": "http://host.docker.internal:8080"
}

### Function CRUD

@function_provider_base_url = http://localhost:9090/provider::function
@function_name = fn1

### Create function

POST {{function_provider_base_url}}/createFunction
content-type: application/json

{
    "key": "{{function_name}}",
    "request": {
        "code": "export const handler = async (event) => { return { statusCode: 200, body: JSON.stringify('Hello!') } };"
    }
}

### Update function

POST {{function_provider_base_url}}/updateFunction
content-type: application/json

{
    "key": "{{function_name}}",
    "request": {
        "code": "export const handler = async (event) => { return { statusCode: 200, body: JSON.stringify('Hola!') } };",
        "timeoutSeconds": 1
    }
}

### Describe function

POST {{function_provider_base_url}}/describeFunction
content-type: application/json

{ "key": "{{function_name}}" }

### Delete function

POST {{function_provider_base_url}}/deleteFunction
content-type: application/json

{ "key": "{{function_name}}" }
